version: 1.0.0 ({build})

environment:
  matrix:
  - PYTHON: C:\Python34
  - PYTHON: C:\Python34-x64
  - PYTHON: C:\Python35
  - PYTHON: C:\Python35-x64
  - PYTHON: C:\Python36
  - PYTHON: C:\Python36-x64
  - PYTHON: C:\Python37
  - PYTHON: C:\Python37-x64

matrix:
  fast_finish: true

clone_depth: 1

build: off

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # - set OPUSENCPATH=c:\opus\opusenc.exe

install:
  - pip install rhvoice-wrapper-bin --only-binary rhvoice-wrapper-bin
  # - appveyor DownloadFile "https://archive.mozilla.org/pub/opus/win32/opus-tools-0.2-win32.zip" -FileName opus.zip
  # - 7z e opus.zip -oc:\opus
  - appveyor AddMessage "Install success"

test_script:
  - ver
  - python -VV
  - python -m unittest discover -v -s rhvoice_wrapper\tests
  - appveyor AddMessage "Testing success"
