version: 1.0.0 ({build})

environment:
  matrix:
  - PYTHON: C:\Python34
  - PYTHON: C:\Python34-x64
  - PYTHON: C:\Python35
  - PYTHON: C:\Python35-x64
  - PYTHON: C:\Python36
    DEPLOY: true
  - PYTHON: C:\Python36-x64
    DEPLOY: true
  - PYTHON: C:\Python37
    PROCESSES_MODE: False
  - PYTHON: C:\Python37-x64
    PROCESSES_MODE: False

matrix:
  fast_finish: true
  allow_failures:
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64

clone_depth: 1

build: off

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # - set OPUSENCPATH=c:\opus\opusenc.exe

install:
  - python -m pip install --upgrade wheel
  - pip install rhvoice-wrapper-bin --only-binary rhvoice-wrapper-bin
  # - appveyor DownloadFile "https://archive.mozilla.org/pub/opus/win32/opus-tools-0.2-win32.zip" -FileName opus.zip
  # - 7z e opus.zip -oc:\opus
  - python setup.py bdist_wheel bdist_wininst --dist-dir=github
  - appveyor AddMessage "Install success"

test_script:
  - ver
  - python -VV
  - python -m unittest discover -v -s rhvoice_wrapper\tests
  - appveyor AddMessage "Testing success"

artifacts:
  - path: github\*
    name: exe

deploy:
  - provider: GitHub
    auth_token:
      secure: ctp+XBxvU4Q/6f55WYYIxUF06CAkiuO3VTUshHz4XWsC/sKTrQyQodIEkgfhvIPF
    on:
      branch: master
      appveyor_repo_tag: true
      DEPLOY: true
