version: 1.0.0 ({build})

environment:
  matrix:
    - platform: x86
      PYTHON: C:\Python34
    - platform: x64
      PYTHON: C:\Python34-x64
    - platform: x86
      PYTHON: C:\Python35
    - platform: x64
      PYTHON: C:\Python35-x64
    - platform: x86
      PYTHON: C:\Python36
    - platform: x64
      PYTHON: C:\Python36-x64
    - platform: x64
      PYTHON: C:\Python37
    - platform: x64
      PYTHON: C:\Python37-x64

matrix:
  fast_finish: true

clone_depth: 1

build: off

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - pip install rhvoice-wrapper-data --only-binary rhvoice-wrapper-data
  - pip install rhvoice-wrapper-bin rhvoice-wrapper-data --only-binary rhvoice-wrapper-bin rhvoice-wrapper-data
  - appveyor DownloadFile "https://archive.mozilla.org/pub/opus/win32/opus-tools-0.2-win32.zip" -FileName opus.zip
  - 7z e opus.zip -oopus
  - appveyor AddMessage "Install success"

test_script:
  - set OPUSENCPATH=%APPVEYOR_BUILD_FOLDER%\opus\opusenc.exe
  - python -m unittest discover -v -s rhvoice_wrapper\tests
  - appveyor AddMessage "Testing success"
