language:
  python
python:
  - '3.5'
  - '3.6'
  - '3.7'
sudo:
  true
install:
  - pip install .
script:
  - python -m unittest discover -v -s rhvoice_wrapper/tests/
before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install --no-install-recommends lame python3 locales opus-tools
  - sudo apt-get -y install --no-install-recommends git scons build-essential python3-pip python3-setuptools
before_script:
  - sudo locale-gen ru_RU.UTF-8
  - git clone https://github.com/Olga-Yakovleva/RHVoice.git
  - cd RHVoice
  - git checkout dc36179
  - scons
  - sudo scons install
  - sudo ldconfig
  - cd ..
